- name: THÊM THÔNG TIN /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    state: present
    block: |
      {{IP_LOADBALANCING}} {{DOMAIN_APP}}
      {{IP_LOADBALANCING}} {{DOMAIN_MANAGER}}

- name: Determine hostname based on position in masters group
  set_fact:
    hostname: "master{{ item }}"
  loop: "{{ range(1, groups['masters']|length + 1)|list }}"
  when: inventory_hostname == groups['masters'][item - 1]

- name: Set the hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
