- name: THÊM THÔNG TIN /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    state: present
    block: |
      {{IP_LOADBALANCING}} {{DOMAIN_APP}}
      {{IP_LOADBALANCING}} {{DOMAIN_MANAGER}}

- name: ĐẶT TÊN HOSTNAME MASTER
  set_fact:
    hostname: "bravo-master{{ item }}"
  loop: "{{ range(1, groups['masters']|length + 1)|list }}"
  when: inventory_hostname == groups['masters'][item - 1]

- name: ĐẶT TÊN HOSTNAME SLAVES
  set_fact:
    hostname: "bravo-slaves{{ item }}"
  loop: "{{ range(1, groups['slaves']|length + 1)|list }}"
  when: inventory_hostname == groups['slaves'][item - 1]

- name: Set the hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
