- name: Check list variable
  hosts: k8s-cluster
  gather_facts: false
  tasks:
    - name: Include variables from var.yaml
      include_vars:
        file: global_vars/var.yaml

- name: CREATE CLUSTER KUBERNETES 
  hosts: k8s-cluster
  roles:
    - pingCheck
    - createFileHost
    # ######################## SETUP CƠ BẢN ####################
    # - setupCommon
    # ######################## CÀI ĐẶT MASTER VÀ JOIN MASTER ####################   
    # - role: createFirstMaster
    #   when: inventory_hostname in groups['masters']
    # - role: joinMasterOther
    #   when: inventory_hostname in groups['masters']
    # ######################## JOIN WORKER ####################
    # - joinWorkerOther
    # # - deleteCommon
