- name: List name record domain
  include_vars:
    file: ../../global_vars/var.yaml

# ############## CHECK THÔNG TIN MASTER  ####################
- name: ============= MASTER =============
  ansible.builtin.set_fact:
    is_first_master: "{{ ansible_play_hosts.index(inventory_hostname) == 0 }}"

- name: ============= WORKER KHÁC =============
  ansible.builtin.set_fact:
    is_other_worker: "{{ inventory_hostname in groups['slaves'] }}"

- name: ============= MASTER =============
  debug:
    var: is_first_master

- name: ============= WORKER KHÁC =============
  debug:
    var: is_other_worker

# # ############## JOIN WORKER VÀO CLUSTER  ####################

# Create token join node
- name: Generate join command
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_command_worker
  when: is_first_master

- name: Export command join cluster
  set_fact:
    command_join_worker_cluster: "{{ kubeadm_join_command_worker.stdout }}"
  when: is_first_master

- name: Export command join cluster
  debug:
    var: command_join_worker_cluster
  when: is_first_master

# JOIN WORKER
- name: JOIN MASTER OTHER IN CLUSTER
  shell: "{{ hostvars[groups['masters'][0]].command_join_worker_cluster }}"
  register: join_worker_output
  when: is_other_worker

- name: XUẤT THÔNG TIN JOIN WORKER
  debug:
    var: join_worker_output
  when: is_other_worker