# Check node Master chính
- name: MASTER ĐẦU TIÊN
  ansible.builtin.set_fact:
    is_first_master: "{{ ansible_play_hosts.index(inventory_hostname) == 0 }}"
    
- name: Debug the value of main master
  debug:
    var: is_first_master


################## CHẠY KHỞI CHẠY CÁC PLUGIN #############

- name: Apply all Kubernetes manifests using kubectl
  shell: |
    kubectl create ns istio-system
    for file in /tmp/script/manifest/*.yaml; do
        kubectl apply -f "$file"
    done
    echo " ================= Cài đặt helm chart ================= "
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh
    kubectl create ns bravo-monitoring
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm repo update
    helm install metrics-k8s-stats prometheus-community/kube-state-metrics --namespace bravo-monitoring --set replicas=2
    helm install node-exporter prometheus-community/prometheus-node-exporter --namespace bravo-monitoring

    echo "================= setup CSI Container ================="
    curl -skSL https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.8.0/deploy/install-driver.sh | bash -s v4.8.0 --

  when: is_first_master
  register: run_manifest

- name: KHỞI CHẠY MANIFEST
  debug:
    var: run_manifest
  when: is_first_master