- name: List name record domain
  include_vars:
    file: ../../global_vars/var.yaml

# Check node Master chính
- name: Check if this is the first master node
  ansible.builtin.set_fact:
    is_first_master: "{{ ansible_play_hosts.index(inventory_hostname) == 0 }}"

- name: Check if this is the first master node
  ansible.builtin.set_fact:
    is_other_master: "{{ ansible_play_hosts.index(inventory_hostname) > 0 }}"

- name: Debug the value of main master
  debug:
    var: is_first_master

- name: Debug the value of other master
  debug:
    var: is_other_master

# Init First Node Master
# - name: Initialize Kubernetes on the first master
#   shell: |
#     kubeadm init \
#       --kubernetes-version=1.28.0 \
#       --control-plane-endpoint="192.168.140.31:6443" \
#       --pod-network-cidr=172.16.0.0/16 \
#       --upload-certs
#   when: is_first_master
#   register: kubeadm_init_output

# - name: Display stdout of the setup script
#   debug:
#     var: kubeadm_init_output.stdout_lines
#   when: is_first_master

#  tạo thư mục service account
# - name: Tạo thư mục service account
#   shell: |
#     mkdir -p $HOME/.kube
#     cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
#     chown $(id -u):$(id -g) $HOME/.kube/config
#   when: is_first_master
#   register: createfolder

# - name: Tạo thư mục service account
#   debug:
#     var: createfolder.stdout_lines
#   when: is_first_master


# Create token join node
- name: Generate join command
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_command
  when: is_first_master

- name: Display the join command
  debug:
    var: kubeadm_join_command.stdout
  when: is_first_master

# Tạo Certificate Join cluster node master
- name: Upload certificates and get certificate key
  shell: kubeadm init phase upload-certs --upload-certs
  register: upload_certs_output
  when: is_first_master

- name: Extract line containing 'Using certificate key:'
  set_fact:
    certificate_key_line: "{{ upload_certs_output.stdout_lines | select('search', 'Using certificate key:') | first }}"
  when: is_first_master

- name: Display certificate key line
  debug:
    var: certificate_key_line
  when: is_first_master

