- name: List name record domain
  include_vars:
    file: ../../global_vars/var.yaml


- name: Check if this is the first master node
  ansible.builtin.set_fact:
    is_first_master: "{{ ansible_play_hosts.index(inventory_hostname) == 0 }}"

- name: Debug the value of is_first_master
  debug:
    var: is_first_master

- name: Initialize Kubernetes on the first master
  shell: |
    kubeadm init \
      --kubernetes-version=1.28.0 \
      --control-plane-endpoint="192.168.140.31:6443" \
      --pod-network-cidr=172.16.0.0/16 \
      --upload-certs
  when: is_first_master
  register: kubeadm_init_output

- name: Display stdout of the setup script
  debug:
    var: kubeadm_init_output.stdout_lines
  when: is_first_master

- name: Extract join command for control plane nodes
  set_fact:
    join_command: "{{ kubeadm_init_output.stdout_lines | select('search', '^kubeadm join') | map('regex_replace', '\\\\', '') | join(' ') }}"
  when: is_first_master

- name: Display stdout of the setup script
  debug:
    var: join_command
  when: is_first_master

- name: Join node to the control plane
  shell: "{{ join_command }}"
  when: ansible_play_hosts.index(inventory_hostname) > 0