- name: Copy setup script to remote server
  copy:
    src: ../../global_vars/script/setup-ubuntu.sh
    dest: /tmp/setup-ubuntu.sh
    mode: "0755"

- name: Run setup script on remote server
  # shell: bash /tmp/setup-ubuntu.sh
  shell: echo "Hello" && /bin/bash /tmp/setup-ubuntu.sh
  register: script_output

- name: Display stdout of the script
  debug:
    var: script_output.stdout  

