- name: Run script setup basic
  script: ../../script/setup-ubuntu.sh v1.28 1.28 0-1.1
  become: yes
  register: script_output

- name: Display stdout of the setup script
  debug:
    var: script_output.stdout_lines