- name: List name record domain
  include_vars:
    file: ../../global_vars/var.yaml

- name: Run script setup basic
  script: ../../script/setup-ubuntu.sh "{{ VERSION_k8s }}" "{{ VERSION_PATCH }}"
  become: yes
  register: script_output

- name: Display stdout of the setup script
  debug:
    var: script_output.stdout_lines