- name: ============= CHECK LIST VARIABLE =============
  include_vars:
    file: ../../global_vars/var.yaml

- name: ============= SETUP CƠ BẢN =============
  script: ../../script/setup-ubuntu.sh "{{ VERSION_k8s }}" "{{ VERSION_PATCH }}"
  become: yes
  register: script_output

- name: ============= THÔNG TIN SETUP CƠ BẢN =============
  debug:
    var: script_output.stdout_lines