- name: List name record domain
  include_vars:
    file: ../../global_vars/var.yaml

# ############## CHECK THÔNG TIN MASTER  ####################
- name: ============= MASTER ĐẦU TIÊN =============
  ansible.builtin.set_fact:
    is_first_master: "{{ ansible_play_hosts.index(inventory_hostname) == 0 }}"

- name: ============= MASTER KHÁC =============
  ansible.builtin.set_fact:
    is_other_master: "{{ ansible_play_hosts.index(inventory_hostname) > 0 }}"

- name: ============= Verify Master Đầu tiên =============
  debug:
    var: is_first_master

- name: ============= Verify Master khác =============
  debug:
    var: is_other_master

# ############## CREATE INFORMATION JOIN CLUSTER  ####################

# Create token join node
- name: ============= Khởi tạo lệnh join master =============
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_command
  when: is_first_master

- name: ============= Lấy thông tin lệnh join =============
  set_fact:
    command_join_cluster: "{{ kubeadm_join_command.stdout }}"
  when: is_first_master

- name: ============= Verify lệnh join master =============
  debug:
    var: command_join_cluster
  when: is_first_master

# Tạo Certificate Join cluster node master
- name: ============= Khởi tạo certificate =============
  shell: kubeadm init phase upload-certs --upload-certs
  register: upload_certs_output
  when: is_first_master

- name: ============= Lấy thông tin certificate =============
  set_fact:
    certificate_key_line: "{{ upload_certs_output.stdout_lines[-1] }}"
  when: is_first_master

- name: ============= Check thông tin certificate =============
  debug:
    var: certificate_key_line
  when: is_first_master

# Gộp lệnh join master
- name: ============= Khởi tạo lệnh join node master =============
  set_fact:
    create_command_join: "{{ kubeadm_join_command.stdout | default('') }} --control-plane --certificate-key {{ upload_certs_output.stdout_lines[-1] | default('') }}"
  when: is_first_master

- name: ============= Verify lệnh join node master ============= 
  debug:
    var: create_command_join
  when: is_first_master

# JOIN MASTER
- name: ============= JOIN MASTER OTHER IN CLUSTER =============
  shell: "{{ hostvars[groups['masters'][0]].create_command_join }}"
  register: join_master_output
  when: is_other_master

- name: join_master_output
  debug:
    var: join_master_output
  when: is_other_master